# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12209ebe56e52b20466a2b2d763b6195134d82544ad4decb630eb7c1e2403aff482c";
    path = fetchzip {
      url = "https://github.com/water-sucks/zignix/archive/31c699f40892ea0ffb144bd8513ae75755a8f0bf.tar.gz";
      hash = "sha256-Io9ZWYb+SamNzjeUWAHuBxhJZXu4TksNjMnKUAOFSHI=";
    };
  }
]
