# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220c74725fb0e865571956dd6004f1e70ef4eb801907155d8411b0bf06b82e510d1";
    path = fetchzip {
      url = "https://github.com/water-sucks/zignix/archive/043e2044345ecfd1f5b542480ad5493244fc0fd5.tar.gz";
      hash = "sha256-0rdVejVe7Ypz+1vHXwrUPY1p8F1JygHJ9ORpmAXjTDM=";
    };
  }
]
